### ISSUE TITLE
Suggestion: make endpoints return dictionaries

### ISSUE THREAD

**Issue by michaelkrukov** [cr-api/cr-api#121]
In my opinion endpoints should always return a dictionaries in order to add consistency to responses. 
For example endpoint `/top/clans` returns list, but if error occurs, it will return dictionary.
I think all endpoints should keep type of returning data and because even on errors server will return a valid json response, consistency in return types should be preserved.

**Comment by selfish** [comment]
Won't happen.
An array is valid JSON, and docs say exactly what to expect. Lists are lists, and I won't wrap them in {}.

Sorry.
