### ISSUE TITLE
Showcase sub

### ISSUE THREAD

**Issue by qubit2** [cr-api/cr-api#143]
- Name of app: "the brews" clan website
- Link to Name of app: http://thebrews.tommaus.com/
- Author(s) of app: Qubit
- Link(s) to author(s) of app: http://thebrews.tommaus.com/player.php?player=PRQJVPCR
- Discord username(s) of author(s) Qubit2#8895
- Description: This website is a homepage for "the brews" clan. This is a very basic example of cr-api usage in a basic clan website that is mobile friendly.

**Comment by selfish** [comment]
I like it!

**Comment by qubit2** [comment]
Thanks!
