### ISSUE TITLE
/top/clans/invalidlocation should return a 404 and not 400

### ISSUE THREAD

**Issue by fourjr** [cr-api/cr-api#167]
Request URL: http://api.cr-api.com/top/clans/invalid

```json
{
  "error": true,
  "status": 400,
  "message": "Invalid location | Additional information and support: http://discord.me/cr_api"
}
```

This is the response given by the API accompanied with a status 400 which from [the docs](http://docs.cr-api.com/#/errors) is a `Bad Request`.    
This should instead be a status 400 which is a `Not Found` as the location key itself is not found.

**Comment by selfish** [comment]
I accept this suggestion (I understand you intended to write 404).
Fixed in the next deployment.
