### ISSUE TITLE
Clan Badges

### ISSUE THREAD

**Issue by ahdavis** [cr-api/cr-api#175]
Can I download all clan badge images from somewhere to minimize network traffic when showing them?

**Comment by jimmyk3008** [comment]
https://github.com/cr-api/cr-api-assets/tree/master/badges

**Comment by LennartKoot** [comment]
You can find all the assets in this repo: [cr-api-assest](https://github.com/cr-api/cr-api-assets)
And specifically the [clan badges](https://github.com/cr-api/cr-api-assets/tree/master/badges).

**Comment by ahdavis** [comment]
Thanks!
