### ISSUE TITLE
Change querystring filters

### ISSUE THREAD

**Issue by kyb3r** [cr-api/cr-api#177]
Instead of `?keys=name,tag`

why not the conventional `?keys=name&keys=tag`
Its easier for us since we can use functions such as urlencode on python to properly format paramters.

**Comment by SoptikHa2** [comment]
I disagree. It's easier to make CSV, and I bet, python has functions to make CSV too. But you do not need functions. You can do simple for cycle, it's 30 seconds of work. It's simplier to use.

```csharp
string query = "?keys=";
string[] fields = new array[] { "name", "currentDeck", "stats" };

// Here comes the CSV - using for cycle
for(int i = 0; i < fields.Length)
    query += fields[i] + ","; // If you wanted to be 100% correct, you wouldn't add "," after the last element
```

**Comment by selfish** [comment]
Starting on version `v7.10.8` API will support both methods.
I had no idea anyone actually preferred the second.
