### ISSUE TITLE
Unauthorized; unknown token

### ISSUE THREAD

**Issue by tracedaily** [cr-api/cr-api#178]
## Request Details:

```
GET
http://api.cr-api.com/clan/28YQ89RY/history
http://api.cr-api.com/players/2CJ2R9C28 (usually fails, but worked 2 or 3 times)
http://api.cr-api.com/clans/2CCCP,2U2GGQJ


```

## Response Details:

```
{u'status': 401, u'message': u'Unauthorized; unknown token | Additional information and support: http://discord.me/cr_api', u'error': True}

```

 1. I just requested my developer key today (10:27 am CST)
 2. Tried the clan history endpoint (python - based on the code example in the docs):
 3. Discord -> !crapikey stats errors with:  Error in command 'crapikey stats'. Check your console or logs for details.
 3. Tried the python wrapper v3.1.6 & 3.1.7 (which is legit, btw. well done Kyb3r) same error: 
 4. Not sure if it matters, but my discord username is treysta#3359

**Comment by selfish** [comment]
Please try again, I believe it should work now. Sorry for the trouble.
It looks like some DB optimizations created a condition where keys take time to become available. Note to self: Eliminate delay after key creation.

**Comment by tracedaily** [comment]
Yep, it's working now, thanks
