### ISSUE TITLE
Discord command !crapikey stats gives false output for today

### ISSUE THREAD

**Issue by SoptikHa2** [cr-api/cr-api#179]
Today, I downloaded total of 6508 player profiles + their clans from your API, that's something about 10 000 requests. But your bot shows something else.

1) About 2 minutes after I started crawler, already had few tens of requests -> no requests shown by bot
2) When I downloaded about 5000th profile -> bot said I made only 1 request
3) When I downloaded about 5010th profile -> bot said I didn't requested today
4) When I downloaded about 5100th profile -> bot said I made only 1 request
5) When I finished -> bot said I made only 1 request

When I used the command before (2.1 dd.mm), it showed correct number of requests.

**Comment by SoptikHa2** [comment]
Today it still thinks I made only 1 request yesterday (5th). I made few requests now and the bot don't know about them.

**Comment by selfish** [comment]
While I'm very very surprised anyone finding out their token is not counted for it's used will report that, you caught a serious issue for us.
Thank you. Fixed. in `v7.10.7`

**Comment by Niwr3** [comment]
It’s still a problem. I have 19 requests a day, and last days it shows 6, 5, 1 and 3.

**Comment by selfish** [comment]
Thanks for the report. Fix is in the works.

**Comment by selfish** [comment]
`v7.10.12` should fix it.
