### ISSUE TITLE
Player profile not updated

### ISSUE THREAD

**Issue by ZeNeLLiE** [cr-api/cr-api#180]
Player profile not updated.

CR-API is showing a old profile. Last battle 6 days ago.
[http://cr-api.com/player/YYVCGJV/battles](url)

For comparison, statsroyale shows updated profile.
[http://statsroyale.com/profile/YYVCGJV/battles](url)

**Comment by selfish** [comment]
Looks like there's an issue with the data we read from the game.
I'll review it. Thanks for the report!

**Comment by selfish** [comment]
Does the issue persist?

**Comment by ZeNeLLiE** [comment]
Yes. The profile has not been updated for over a week.

**Comment by selfish** [comment]
Fixed in `v7.11.6` :)
