### ISSUE TITLE
Dev key reports broken

### ISSUE THREAD

**Issue by selfish** [cr-api/cr-api#183]
Since friday

Created by: `Selfish`

**Comment by selfish** [comment]
Fixed in `v7.10.10`

**Comment by fourjr** [comment]
Can this get reopened? in the latest one, total registered keys shows undefined.

**Comment by fourjr** [comment]
I'm guessing this got fixed in `v7.11.2` but I'll follow up tomorrow.

**Comment by fourjr** [comment]
@selfish @smlbiobot The issue isn't fixed yet?
