### ISSUE TITLE
Clan History donation error

### ISSUE THREAD

**Issue by paoloalby** [cr-api/cr-api#187]
## Issue Report:
 1. The "donations" value, for each member, log after log, it supposed to increment. But after the first 2 logs, the value of "donations" is starting over
 2. https://cr-api.com/clan/2GVJCJ/history
 3. You can check the problem at that link. 
Look, for example, 
Alessandro (38, 94, and then back to 58..), 
or BeviH2O (68, 168, and then back to 76),
or Chry (48, 206 and then back to 104)

**Comment by paoloalby** [comment]
A new problem this morning:
all the data collected about my clan has vanished.
If I check on your website (https://cr-api.com/clan/2GVJCJ/history), I see this message:

> Your clan has not yet enabled clan history.
> 
> Clan history is an excellent way to for clans to track activity over time. However, it is not enabled by default. In order to enable it, add the URL RoyaleAPI.com in your clan description and we will start tracking it.

**Comment by selfish** [comment]
This is a weekly count, so the drop is legit.

**Comment by selfish** [comment]
In general, the current UI is temporary, and will be improved with time.
But as for the data, I believe it is complete and sound.
