### ISSUE TITLE
Wrong clanChest status during a running clanchest

### ISSUE THREAD

**Issue by taky-taky** [cr-api/cr-api#195]
I am fetching the clan data periodically.
During a running clanchest I got active, inactive, active status from the api>
This is for sure because I saved the responses into files..
!!!REMARK!!! Sometimes I got crapy trophies also for people in my clan but I dont have those jsons.

cat '2018-01-13 **20:50:00**-clan.json' | jq
{
  "tag": "2U8U0P20",
...  
 "clanChest": {
    "status": "**active**"

cat '2018-01-13 **21:00:00**-clan.json' | jq
{
  "tag": "2U8U0P20",
...  
 "clanChest": {
    "status": “**inactive**"

cat '2018-01-13 **21:10:00**-clan.json' | jq
{
  "tag": "2U8U0P20",
...
  "clanChest": {
    "status": “**active**"

**Comment by taky-taky** [comment]
Forgot to mention. This happened not just once.

**Comment by selfish** [comment]
Sorry for the lame response, but this is data read from the game.
We pass it on as we receive it. No can do at the time.
