### ISSUE TITLE
Log clan chest status in clan history

### ISSUE THREAD

**Issue by selfish** [cr-api/cr-api#196]
Created by: `Selfish`

**Comment by Kadargo94** [comment]
I'm not sure about creating a new feature request or if it's linked to this one.
That would be great if we could get the number of crowns per player for the clan chest with a proper GET request.

**Comment by fourjr** [comment]
Create another issue for that next time, to answer your question:

The `/clan/:tag ` endpoint already provides the information.

`members ` is an array which contains the `clanChestCrowns` which is what you want.

**Comment by selfish** [comment]
Added in `v10.6`
