### ISSUE TITLE
API Down restart needed iirc

### ISSUE THREAD

**Issue by fourjr** [cr-api/cr-api#198]
Maintenance ended a couple hours ago.

**Comment by TheLearneer** [comment]
I dont know why does the API needs some manual restart after maintenance break.
But I assume putting the whole code of obtaining data inside a `try-catch` block would help out somehow,
or maybe using `setinterval` if there is error obtaining data from the app.

Its just my idea, as I dont know how the data is fetched from the app.

**Comment by selfish** [comment]
Trust me, the issue is somewhat more elaborate than that.
Also, while the auto-recovery time is long, why tf do you assume I do stuff manually? That's what code is for.
