### ISSUE TITLE
Request: Remove Achievements from Player Endpoint

### ISSUE THREAD

**Issue by PixelCrux** [cr-api/cr-api#206]
I would like to request that the achievements portion of the data for players be removed from the API. It's a bit minor, but the reason I ask this is since achievements are no longer in the game, having them in the data only increases storage and transfer costs. Thank you!

**Comment by selfish** [comment]
Add `?exclude=achievements` to your requests, and poof!

**Comment by PixelCrux** [comment]
Ah! Thank you.
