### ISSUE TITLE
no data from Clan History since yesterday

### ISSUE THREAD

**Issue by paoloalby** [cr-api/cr-api#210]
## Request Details:

```
GET
http://api.cr-api.com/clan/2GVJCJ/history
```

## Issue Report:
the last log of my clan 2GVJCJ it's from yesterday morning at 8:00.
It supposed to have 6 more logs, one every 4 hours.
Did you stop the log from clan history?

**Comment by selfish** [comment]
Should be back now.
The gap.will remain as we completely reworked the infrastructure and had some difficulties. Sorry.
