### ISSUE TITLE
Website is banned 

### ISSUE THREAD

**Issue by ShipDeveloper** [cr-api/cr-api#224]
Sir, is my site address banned?
I can not access the Api server.

Web URL : http://oyungemisiytb.com

**Comment by fourjr** [comment]
Did your site exceed the ratelimits? Check if there's an error code of `429` being returned by the API

**Comment by ShipDeveloper** [comment]
It was overrun by DDOS attack. I made the necessary arrangements.

**Comment by fourjr** [comment]
did you have that status code in the api response?

**Comment by ShipDeveloper** [comment]
Sorry, the page is blank, I did not see the code.

http://oyungemisiytb.com/veri.php

**Comment by selfish** [comment]
As we spoke, it's not.
