### ISSUE TITLE
Is there any problem with crapikey??

### ISSUE THREAD

**Issue by sanjuand** [cr-api/cr-api#233]
## Request Details:

```
GET
http://api.cr-api.com/clan/8R28VQ9P,89YV8UR8
```

## Response Details:

```
{
    "error": true,
    "status": 401,
    "message": "Unauthorized; unknown token | Additional information and support: http://discord.me/cr_api"
}

```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there?
 2. Expected behaviour: 
 3. Console logs (if applicable): 
 4. Screenshots (if applicable):

**Comment by sanjuand** [comment]
Yes I’m

iPhone

**Comment by selfish** [comment]
There's no issue. You need to provide the header properly.
I checked your key and it is valid and working.

**Comment by sanjuand** [comment]
Is it possible that I send the key to my email? I don't receive it into the MD and I don't know what is my key, the issue in my case is that the key doesn't reach into my MD

**Comment by fourjr** [comment]
Do you have DMs enabled in the cr-api server? If you do not, enable it and do `!crapikey get` once again and it should be DM-ed to you by the bot.

**Comment by sanjuand** [comment]
![image](https://user-images.githubusercontent.com/35265781/36141198-2d6a2900-10a4-11e8-9a13-af16d2c24deb.png)

**Comment by sanjuand** [comment]
![image](https://user-images.githubusercontent.com/35265781/36141249-56aaeb56-10a4-11e8-8772-303c02692c0d.png)

**Comment by fourjr** [comment]
@smlbiobot Can you look into this?

**Comment by sanjuand** [comment]
I enable DMs in the cr-api server, but this MDs doesn't get to me

**Comment by sanjuand** [comment]
Sorry, but I don't receive MD from you, I receive MD from a lot of people, but your MDs don't get to me.

**Comment by sanjuand** [comment]
@fourjr I send you a MD, for proof

**Comment by fourjr** [comment]
DM `4JR#4895 ` not fourjr

**Comment by sanjuand** [comment]
resend

**Comment by fourjr** [comment]
Resolved.

**Comment by sanjuand** [comment]
A lot of Thanx Guys
