### ISSUE TITLE
Error in clan search & friendly fights in clan

### ISSUE THREAD

**Issue by GameDeve1oper** [cr-api/cr-api#235]
Good afternoon! Could you correct the search for clans and friendly fights in the clans? Basically, the search for clans yields the result, or nothing is found, or an error. Rarely does the clans themselves search for parameters. And clan battles when asked in api just give an error and are rarely displayed.

**Comment by fourjr** [comment]
Could you give some sample URLs that you've tried? and the error responses along with the URLs

**Comment by selfish** [comment]
Please report issues using the template provided when creating a new issue. I can't reproduce this without an example. Everything seems to be ok from my end.
