### ISSUE TITLE
Some /clan/search is returning non-JSON-able data

### ISSUE THREAD

**Issue by fourjr** [cr-api/cr-api#236]
URLs I tried:
- http://api.cr-api.com/clan/search?name=abc ([Hastebin](https://hastebin.com/eganoveqin.json))
- http://api.cr-api.com/clan/search?name=magic ([Hastebin](https://hastebin.com/qukupinemo.json))
- http://api.cr-api.com/clan/search?name=lol ([Hastebin](https://hastebin.com/azakezuvul.json))
- http://api.cr-api.com/clan/search?name=haha ([Hastebin](https://hastebin.com/naxihusehi.json))

These worked:
- http://api.cr-api.com/clan/search?name=4jr (Returned a 200, normal response)
- http://api.cr-api.com/clan/search?name=lmao (Returned a 200, [Hastebin](https://hastebin.com/oqojuxuzag.json))
- http://api.cr-api.com/clan/search?name=nobodyname (Returned a 404, clans not found)

Firefox and Python's `requests` lib both were both unable to parse the JSON
![Firefox](https://user-images.githubusercontent.com/28086837/36140033-cd6ad6a8-10da-11e8-9028-d733e8ca16d6.png)
Above is a picture of Firefox's response for `name=abc`

**Comment by selfish** [comment]
Resolved in `v10.2.17`
