### ISSUE TITLE
/populars/players first response being blank

### ISSUE THREAD

**Issue by fourjr** [cr-api/cr-api#238]
http://api.cr-api.com/popular/players first response has no `Player` object.     
Pretty sure this is the statistics from `http://api.cr-api.com/players/` and it should be filtered out in my opinion.
![image](https://user-images.githubusercontent.com/28086837/36140976-1f9488f4-10de-11e8-83e3-8dc2f7be2b9a.png)

**Comment by selfish** [comment]
Fixed in `v10.2.17`
