### ISSUE TITLE
fields="chests" returns null ~

### ISSUE THREAD

**Issue by assisboy** [cr-api/cr-api#250]
## Request Details:

```
GET
http://api.cr-api.com/player/{$player}?keys=chests
```

## Response Details:

```
Code: 200

[...]

```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there?
 2. Expected behaviour: 
 3. Console logs (if applicable): 
 4. Screenshots (if applicable):

**Comment by fourjr** [comment]
Use this URL instead 

http://api.cr-api.com/player/2P0LYQ?keys=chestCycle
