### ISSUE TITLE
Create constants endpoint

### ISSUE THREAD

**Issue by selfish** [cr-api/cr-api#251]
Created by: `Selfish`

**Comment by fourjr** [comment]
I'll just put this here for the time being:
https://fourjr-webserver.herokuapp.com/cr/constants

**Comment by selfish** [comment]
I meant include the code. :X
I don't want the api to rely on external services.

**Comment by fourjr** [comment]
haha its python but https://github.com/fourjr/webserver/blob/master/webserver.py

the bs4 part can most likely be improved with the github api but i couldn't be bothered to at that time

**Comment by selfish** [comment]
Added in `v10.6`
