### ISSUE TITLE
Clan Search: When nothing found, return empty array insted of throwing error

### ISSUE THREAD

**Issue by SoptikHa2** [cr-api/cr-api#256]
Hello, when I request from Clan Search endpoint, with something like

name: "necocofaktvubecanitrochuneexistuje" (some random string)
score: any
minMembers: any
maxMembers: any

no clans with this settings exists. Could you just return empty array instead of throwing Not Found error? It'd be much easier to use and would make more sense. When nothing is found, it isn't error state, just return nothing.

Is this possible?

Thanks, Soptik

**Comment by selfish** [comment]
It's possible, but it makes no sense.
This is not an SDK, and the API cannot `throw` errors.
It returns a status code indicating nothing was found.

This is how APIs usually communicate, but status codes.
What's clearer than "not found"?
