### ISSUE TITLE
A few questions regarding Rate Limits

### ISSUE THREAD

**Issue by fourjr** [cr-api/cr-api#257]
## What is currently understood
There are 2 headers provided by the API:

Header | Example Value
-- | --
x-ratelimit-limit | 260
x-ratelimit-remaining | 258

Ratelimits are at 250 requests/1 minute window
Ratelimits are by developer key

## What I want to ask
1. Does `https://api.cr-api.com/player/<TAG>,<TAG>,<TAG>` count as 3 requests?
2. What is the response of a ratelimited request? Status is `420 Too Many Requests`? What's the JSON Response?
3. Is being ratelimited counted as having `0` in `x-ratelimit-remaining`?
4. Do all authenticated endpoints count as 1 request (except question 1)? Or are there some that count as more and some that count as less?

## Why I'm asking
I want to implement ratelimit handling in https://www.github.com/cgrok/clashroyale

**Comment by selfish** [comment]
1. Currently single, future: multi.
2. `429` - can't recall the response, it'll be an error: true smth. Easiest is to just hit the cap and see.
3. Yes.
4. Currently all are 1, aside from `/auth/stats` which is not counted.

All of this is subject to change of course.
I'll try to use this issue as a place to update regarding tweaks.
Naturally, all tweaks and changes derive from stability needs.

**Comment by fourjr** [comment]
Here's the repsonse for anyone that wants it:
```json
{
    "error": true,
    "status": 429,
    "message": "Rate limit reached | Additional information and support: http://discord.me/cr_api"
}
```
