### ISSUE TITLE
Showcase - Clash Royale Dicas Stats

### ISSUE THREAD

**Issue by xlucasfelix** [cr-api/cr-api#258]
- Clash Royale Dicas Stats
- https://www.clashroyaledicas.com/stats/
- play.google.com/store/apps/details?id=com.clashdicas.clashroyaledicas (will be added to the app soon)
- Lucas Felix (developed by Reginaldo P.)
- https://twitter.com/ClashDicas
- ClashDicas - Lucas Felix#1019
- Profile statistics tool for the Brazilian Clash Royale community

**Comment by fourjr** [comment]
This issue was moved to cr-api/cr-api-docs#9
