### ISSUE TITLE
Showcase - Clash Royale Chest Tracker

### ISSUE THREAD

**Issue by nelsonalmendra** [cr-api/cr-api#259]
- Name of app: Clash Royale Chest Tracker
- Link to Name of app: https://play.google.com/store/apps/details?id=com.nelsonalmendra.clashroyalechesttracker
- Author(s) of app: Nelson Almendra
- Link(s) to author(s) of app: https://twitter.com/NelsonAlmendra
- Discord username(s) of author(s): Illusionpt
- Description: Simple way to keep tracking of the next chests.

**Comment by fourjr** [comment]
This issue was moved to cr-api/cr-api-docs#8
