### ISSUE TITLE
cloudflare 520: Web server is returning an unknown error

### ISSUE THREAD

**Issue by AmirSavand** [cr-api/cr-api#269]
I was working with API yesterday and all went well but last night I started seeing a lot of delay in requests and I decided that I need to use cache.

But today, it seems that the loading is infinite... All requests, /clan and /player.

**Comment by AmirSavand** [comment]
It seriously doesn't load at all... I'm getting no response, I'll try changing my access token.

**Comment by AmirSavand** [comment]
I checked more and the problem was on my side, I wasn't handling it right.

I will reopen if this happened again.

**Comment by AmirSavand** [comment]
Ok, after I checked again, sometimes the requests go well and sometimes they don't. I took a look and it was your server, I got error *api.cr-api.com | 520: Web server is returning an unknown error*

**Comment by fourjr** [comment]
What are the full urls you are requesting?

**Comment by AmirSavand** [comment]
@fourjr:
`http://api.cr-api.com/clan/2Y2C9RCJ/?keys=members`

**Comment by AmirSavand** [comment]
The error is from your side by **cloudflare** any updates?

**Comment by fourjr** [comment]
This is due to the API being down. Refer to #status

**Comment by AmirSavand** [comment]
This is terrible news, thanks for responding.
