### ISSUE TITLE
New Website using API (Showcase Request)

### ISSUE THREAD

**Issue by Samisage** [cr-api/cr-api#273]
Name of App: Clanstats (NOTE: Currently designed for the clan "Chapsters" but these are early stages.)
Link: http://samisage.com/app/clanstats/
Authors: Samisage, bobbob (aka. Ujimaflip), ma
Link to Author: http://samisage.com
Discord Usernames: Samisage#7684 , ujimaflip#9369 , ma#7333

Description:

Features of this website for the clan "Chapsters", Includes:

Graphs of users combined stats,
Clickable user names to see stats of specific user,
Utilities for members of the clan,
Leader board on the front page.

[All Stats are updated every 5 minutes and are stored in a database so if the API isn't working the latest data will be shown.]

Graphs example:
http://samisage.com/u/15.50.20-06.03.18.leader
http://samisage.com/u/15.50.34-06.03.18.timeline

If you're not in the Chapsters clan, consider checking it out or check back in a while to see if we've changed the way the website works.

**Comment by fourjr** [comment]
This issue was moved to cr-api/cr-api-docs#13
