### ISSUE TITLE
Setup proper error codes

### ISSUE THREAD

**Issue by selfish** [cr-api/cr-api#30]

**Comment by SOSkr** [comment]
It would be really good if the API responded errors,

for example:

You can not find the Tag (404)
Server is not responding (403, 500, 503)
In maintenance work (maybe 204)

**Comment by selfish** [comment]
Minor improvements in errors implemented in `v3.0.6`, still can't figure a better way to do it.

**Comment by selfish** [comment]
Closing as less-informative dup of #29
