### ISSUE TITLE
isCountry from Clan, boolean?

### ISSUE THREAD

**Issue by fourjr** [cr-api/cr-api#78]
![image](https://user-images.githubusercontent.com/28086837/32170954-ab8976c4-bdb1-11e7-8c61-7533e60defc2.png)

The above screenshot is from [this clan object](http://api.cr-api.com/clan/29UQQ282).

`isCountry` is currently a string, `"true"` or `"false"`, it'll be better if its a boolean

**Comment by selfish** [comment]
Good catch, will correct in next release.

**Comment by selfish** [comment]
Fixed.
