### ISSUE TITLE
Feature Request: Add A Tournaments Endpoint

### ISSUE THREAD

**Issue by kyb3r** [cr-api/cr-api#86]
Would it be possible to add an endpoint that lists currently open tournaments?
`https://api.cr-api.com/tournaments/<TAG>`
`https://api.cr-api.com/tournaments/free`

**Comment by selfish** [comment]
We want it very much. :)

**Comment by selfish** [comment]
Added in v7.1.0 excluding open tournaments, sadly we currently can't reach this list.
Will be added if we can.
