### ISSUE TITLE
clanChest returns values higher than the cap

### ISSUE THREAD

**Issue by fourjr** [cr-api/cr-api#98]
![image](https://cdn.discordapp.com/attachments/365876792080334849/384382777572720650/Screen_Shot_2017-11-27_at_12.39.47_AM.png) Coming from http://api.cr-api.com/clan/28JU8P0Y

I think this happens if a user gets a 3 crown win when the clan is at 1599 crowns. Auto-rounding it to the capacity would be my idea of a "fix"

**Comment by jmibegi2h** [comment]
that's how it appears in Clash Royale, if you do not like it, then you can round it up on your server

**Comment by Gr8z** [comment]
You can use a max function in your apps to fix this. I don't think we should manipulate the data in the API, some people might need this info.

**Comment by fourjr** [comment]
oh, didn't know it appears like that in-game. okay then!
